<?php

$stArray = array(
		array("val" => "AL", "text" => "Alabama"),
		array("val" => "AK", "text" => "Alaska"),
		array("val" => "AZ", "text" => "Arizona"),
		array("val" => "AR", "text" => "Arkansas"),
		array("val" => "CA", "text" => "California"),
		array("val" => "CO", "text" => "Colorado"),
		array("val" => "CT", "text" => "Connecticut"),
		array("val" => "DE", "text" => "Delaware"),
		array("val" => "DC", "text" => "District of Columbia"),
		array("val" => "FL", "text" => "Florida"),
		array("val" => "GA", "text" => "Georgia"),
		array("val" => "HI", "text" => "Hawaii"),
		array("val" => "ID", "text" => "Idaho"),
		array("val" => "IL", "text" => "Illinois"),
		array("val" => "IN", "text" => "Indiana"),
		array("val" => "IA", "text" => "Iowa"),
		array("val" => "KS", "text" => "Kansas"),
		array("val" => "KY", "text" => "Kentucky"),
		array("val" => "LA", "text" => "Louisiana"),
		array("val" => "ME", "text" => "Maine"),
		array("val" => "MD", "text" => "Maryland"),
		array("val" => "MA", "text" => "Massachusetts"),
		array("val" => "MI", "text" => "Michigan"),
		array("val" => "MN", "text" => "Minnesota"),
		array("val" => "MS", "text" => "Mississippi"),
		array("val" => "MO", "text" => "Missouri"),
		array("val" => "MT", "text" => "Montana"),
		array("val" => "NE", "text" => "Nebraska"),
		array("val" => "NV", "text" => "Nevada"),
		array("val" => "NH", "text" => "New Hampshire"),
		array("val" => "NJ", "text" => "New Jersey"),
		array("val" => "NM", "text" => "New Mexico"),
		array("val" => "NY", "text" => "New York"),
		array("val" => "NC", "text" => "North Carolina"),
		array("val" => "ND", "text" => "North Dakota"),
		array("val" => "OH", "text" => "Ohio"),
		array("val" => "OK", "text" => "Oklahoma"),
		array("val" => "OR", "text" => "Oregon"),
		array("val" => "PA", "text" => "Pennsylvania"),
		array("val" => "RI", "text" => "Rhode Island"),
		array("val" => "SC", "text" => "South Carolina"),
		array("val" => "SD", "text" => "South Dakota"),
		array("val" => "TN", "text" => "Tennessee"),
		array("val" => "TX", "text" => "Texas"),
		array("val" => "UT", "text" => "Utah"),
		array("val" => "VT", "text" => "Vermont"),
		array("val" => "VA", "text" => "Virginia"),
		array("val" => "WA", "text" => "Washington"),
		array("val" => "WV", "text" => "West Virginia"),
		array("val" => "WI", "text" => "Wisconsin"),
		array("val" => "WY", "text" => "Wyoming")
);

echo(json_encode($stArray));